general {
    ignore_dbus_inhibit = false
}

listener {
    timeout = 60
    # Pas 1 menit idle, panggil wrapper script
    on-timeout = ~/.config/hypr/run_aod.sh
    
    # Pas trackpad/mouse digeser, paksa tutup seketika
    on-resume = killall -SIGUSR1 hyprlock
}

# Tambahan (Opsional): Kalau 5 menit beneran ditinggal, matikan layar
#listener {
#    timeout = 300
#    on-timeout = hyprctl dispatch dpms off
#    on-resume = hyprctl dispatch dpms on
#}
