general {
    disable_loading_bar = true
}

background {
    monitor =
    color = rgba(0, 0, 0, 1.0)
}

label {
    monitor =
    text = cmd[update:60000] ~/.config/hypr/aod_shift.sh
    color = rgba(255, 255, 255, 1.0)
    font_size = 45
    font_family = monospace
    position = 0, 0
    halign = center
    valign = center
}
